version: '3.8'

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    container_name: soporte_db
    env_file:
      - .env  # Carga variables desde .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - soporte_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soporte_backend
    env_file:
      - .env  # Carga variables desde .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - soporte_network
    volumes:
      - ./backend/app:/app
    restart: unless-stopped

  # Servicio Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: soporte_frontend
    ports:
      - "89:80"
    depends_on:
      - backend
    networks:
      - soporte_network
    restart: unless-stopped

networks:
  soporte_network:
    driver: bridge

volumes:
  mysql_data: